"""Add meeting.data JSONB column

Revision ID: dc59a1c03d1f
Revises: 
Create Date: 2025-06-07 21:50:48.189571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc59a1c03d1f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL to add column if it doesn't exist to prevent crash loops
    op.execute("ALTER TABLE meetings ADD COLUMN IF NOT EXISTS data JSONB NOT NULL DEFAULT '{}'::jsonb")
    # Only create index if it doesn't exist
    op.execute("CREATE INDEX IF NOT EXISTS ix_meeting_data_gin ON meetings USING gin (data)")
    
    op.execute("UPDATE meetings SET data = '{}'::jsonb WHERE data IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meeting_data_gin', table_name='meetings', postgresql_using='gin')
    op.drop_column('meetings', 'data')
    # ### end Alembic commands ### 